### PR TITLE
Add python binding for the library

### PR DESCRIPTION
**Pull request by tfiedor**
This Pull Requests:
  1. Adds python binding for the library, so it can be used from the Python (either for prototyping or real application).
  2. Provides github action to test the buildability and usability.
  3. Demonstrate examples of using the library in the Python.

### CODE REVIEW

**Comment by tfiedor** [comment]
> > > Is it really necessary to have the strict match for the package version in `requirements.txt`? Isn't it more suitable to have, e.g, >=?
> > 
> > 
> > It's not necesary, I could change it, but there might be some (future) dependency hell. This was just an output of `pip3 freeze`
> 
> If we are using mainly some basic features where there is a small probability of future changes in the packages, I maybe lean towards the change. It is somehow strange to have demands for minor versions of packages. But yes, it may cause dependency problems (if this happens, we could fix the versions later, no?)

Yeah, sure.

**Comment by vhavlena** [comment]
I maybe have another two remarks: Could the `to_dot` method provide a possibility of returning the automaton in dot format as a string? Also is it somehow possible to provide the `__str__` method for Nfa? Both would be very useful for debugging purposes.

**Comment by tfiedor** [comment]
Sure. Will initial states, final states and transitions suffice in str()?

**Comment by vhavlena** [comment]
maybe plus the alphabet map (mapping between numbers and "real" symbols)?

**Comment by tfiedor** [comment]
Some of the new functionality is still missing, but I will write it when I'm back from holiday.

Currently all of the original functionality of Ondra's library should be supported, creation of NFA from regexes, three different alphabets (DirectAlphabet is not supported, it seems to be useless), output of automata to dot string, dot file and simple string. Probably some bugs will be still there (mostly issues with encoding, IMO). Some of the function takes `encoding` as parameter, so one might need to try several different encodings in case there are problems.

Finally, there is `example.ipynb` jupyter notebook that display very simple usage of the library.

**Review by martinhruska — APPROVED** [review]
I have no problems with pull request. I think we can take it as it is and merge it to devel branch.

**Pull request merged**
